name: Verify Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Demonized wiki Docker image
      run: |
        docker build -t demonized-wiki ./
